// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProgettoSpesa.EF
{
    public partial class TListaSpesa
    {
        public long Id { get; set; }
        public string Prodotto { get; set; }
        public int Quantita { get; set; }
        public decimal Prezzo { get; set; }
    }
}