// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ProgettoSpesa.EF;

#nullable disable

namespace ProgettoSpesa.Data
{
    public partial class SpesaContext : DbContext
    {
        public SpesaContext()
        {
        }

        public SpesaContext(DbContextOptions<SpesaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TListaSpesa> TListaSpesa { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<TListaSpesa>(entity =>
            {
                entity.ToTable("T_Lista_Spesa");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Prezzo)
                    .HasColumnType("money")
                    .HasColumnName("prezzo");

                entity.Property(e => e.Prodotto)
                    .IsRequired()
                    .HasMaxLength(250)
                    .IsUnicode(false)
                    .HasColumnName("prodotto");

                entity.Property(e => e.Quantita).HasColumnName("quantita");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}